#!/usr/bin/env bash
set -euo pipefail
SOURCE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${HOME}/.local/bin"
CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/nesus-ai"
mkdir -p "$BIN_DIR" "$CONFIG_DIR"
install -m 0755 "$SOURCE_DIR/nesus_ai.py" "$BIN_DIR/nesus_ai"
ln -sfn "$BIN_DIR/nesus_ai" "$BIN_DIR/nesus-ai"
install -m 0755 "$SOURCE_DIR/launch.py" "$BIN_DIR/nesus-ai-launch"
install -m 0755 "$SOURCE_DIR/stop.py" "$BIN_DIR/nesus-ai-stop"
[[ -f "$CONFIG_DIR/config.toml" ]] || install -m 0600 "$SOURCE_DIR/config.example.toml" "$CONFIG_DIR/config.toml"
[[ -f "$CONFIG_DIR/secrets.env" ]] || install -m 0600 "$SOURCE_DIR/secrets.example.env" "$CONFIG_DIR/secrets.env"
[[ -f "$CONFIG_DIR/instructions.md" ]] || install -m 0600 "$SOURCE_DIR/instructions.md" "$CONFIG_DIR/instructions.md"
chmod 600 "$CONFIG_DIR/secrets.env" "$CONFIG_DIR/config.toml" "$CONFIG_DIR/instructions.md"
echo "Installed. Configure keys in: $CONFIG_DIR/secrets.env"
echo "Then run: nesus_ai doctor"
echo "Add Google/proxy: nesus_ai add-provider"
